version: "3.8"
services:
  front:
    hostname: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - "3000:3000"
    tty: true
